# Generated by Django 6.0.5 on 2026-06-04 00:35

import django.core.validators
import django.db.models.deletion
import procurement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id_origem', models.AutoField(primary_key=True, serialize=False, verbose_name='ID da Origem')),
                ('unidade', models.CharField(max_length=15, unique=True, verbose_name='Unidade')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Origem',
                'verbose_name_plural': 'Origens',
                'db_table': 'origem',
                'ordering': ['unidade'],
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id_servidor', models.CharField(help_text='Matrícula funcional do servidor (apenas números)', max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_matricula', message='A matrícula deve conter apenas números.', regex='^\\d+$')], verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'db_table': 'servidor',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id_processo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Processo')),
                ('numero_sei', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_numero_sei', message='O número SEI deve conter apenas números.', regex='^\\d+$')], verbose_name='Número SEI')),
                ('categoria', models.CharField(choices=[('CS', 'Custeio'), ('IN', 'Investimento')], max_length=2, verbose_name='Categoria Econômica')),
                ('data_recebimento', models.DateField(verbose_name='Data de Recebimento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_servidor', models.ForeignKey(db_column='id_servidor', on_delete=django.db.models.deletion.PROTECT, to='procurement.servidor', verbose_name='Servidor Responsável')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'db_table': 'processo',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Setor')),
                ('nome_setor', models.CharField(max_length=20, verbose_name='Nome do Setor')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_origem', models.ForeignKey(db_column='id_origem', on_delete=django.db.models.deletion.PROTECT, to='procurement.origem', verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'db_table': 'setor',
                'ordering': ['id_origem', 'nome_setor'],
            },
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id_termo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Termo')),
                ('rotulo', models.CharField(max_length=6, verbose_name='Rótulo')),
                ('ano', models.IntegerField(default=procurement.models.ano_atual, verbose_name='Ano')),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo')], default='AT', max_length=2, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_processo', models.ForeignKey(db_column='id_processo', on_delete=django.db.models.deletion.PROTECT, to='procurement.processo', verbose_name='Processo')),
                ('id_setor', models.ForeignKey(db_column='id_setor', on_delete=django.db.models.deletion.PROTECT, to='procurement.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Termo',
                'verbose_name_plural': 'Termos',
                'db_table': 'termo',
                'ordering': ['-ano', 'rotulo'],
            },
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['numero_sei'], name='processo_numero__e26b61_idx'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['data_recebimento'], name='processo_data_re_4747ff_idx'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['id_servidor'], name='processo_id_serv_f6408c_idx'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['categoria'], name='processo_categor_156d85_idx'),
        ),
        migrations.AddConstraint(
            model_name='setor',
            constraint=models.UniqueConstraint(fields=('id_origem', 'nome_setor'), name='unique_setor_por_origem'),
        ),
        migrations.AddIndex(
            model_name='termo',
            index=models.Index(fields=['id_processo'], name='termo_id_proc_47086a_idx'),
        ),
        migrations.AddIndex(
            model_name='termo',
            index=models.Index(fields=['status'], name='termo_status_534b66_idx'),
        ),
        migrations.AddIndex(
            model_name='termo',
            index=models.Index(fields=['ano'], name='termo_ano_8898ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='termo',
            constraint=models.UniqueConstraint(fields=('id_setor', 'rotulo', 'ano'), name='unique_rotulo_por_setor_e_ano'),
        ),
    ]
