# Generated by Django 6.0.1 on 2026-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('matricula', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Número de Matrícula')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
    ]
