# Generated by Django 6.0.5 on 2026-06-01 21:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id_servidor', models.CharField(help_text='Matrícula funcional do servidor (apenas números)', max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_matricula', message='A matrícula deve conter apenas números.', regex='^\\d+$')], verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'db_table': 'servidor',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id_processo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Processo')),
                ('numero_sei', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_numero_sei', message='O número SEI deve conter apenas números.', regex='^\\d+$')], verbose_name='Número SEI')),
                ('categoria', models.CharField(choices=[('CS', 'Custeio'), ('IN', 'Investimento')], default='CS', max_length=2, verbose_name='Categoria Econômica')),
                ('data_recebimento', models.DateField(verbose_name='Data de Recebimento')),
                ('id_servidor', models.ForeignKey(db_column='id_servidor', on_delete=django.db.models.deletion.PROTECT, to='procurement.servidor', verbose_name='Servidor Responsável')),
            ],
        ),
    ]
