# Generated by Django 6.0.1 on 2026-04-01 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('cotacao', models.AutoField(primary_key=True, serialize=False)),
                ('processo_sei', models.CharField(max_length=30, unique=True, verbose_name='Processo SEI')),
                ('numero_tr', models.CharField(max_length=10, verbose_name='Número do TR')),
                ('origem_tr', models.CharField(max_length=20, verbose_name='Origem do TR')),
                ('unidade', models.CharField(max_length=20, verbose_name='Unidade')),
                ('categoria_economica', models.CharField(max_length=30, verbose_name='Categoria Econômica')),
                ('data', models.DateField(verbose_name='Data de Recebimento')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='procurement.servidor', verbose_name='Servidor Responsável')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'db_table': 'processo',
                'ordering': ['-data', 'processo_sei'],
                'indexes': [models.Index(fields=['data'], name='idx_processo_data'), models.Index(fields=['servidor'], name='idx_processo_servidor'), models.Index(fields=['categoria_economica'], name='idx_processo_categoria')],
            },
        ),
    ]
