# Generated by Django 6.0.5 on 2026-06-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id_origem', models.AutoField(primary_key=True, serialize=False, verbose_name='ID da Origem')),
                ('unidade', models.CharField(max_length=15, unique=True, verbose_name='Unidade')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Origem',
                'verbose_name_plural': 'Origens',
                'db_table': 'origem',
                'ordering': ['unidade'],
            },
        ),
    ]
