# Generated by Django 6.0.5 on 2026-06-04 00:39

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER unique_termo_ativo_por_processo_insert
                AFTER INSERT ON termo
                WHEN NEW.status = 'AT'
                BEGIN
                    UPDATE termo 
                    SET status = 'IN'
                    WHERE id_processo = NEW.id_processo
                    AND status = 'AT'
                    AND id_termo != NEW.id_termo;
                END;

                CREATE TRIGGER unique_termo_ativo_por_processo_update
                AFTER UPDATE ON termo
                WHEN NEW.status = 'AT'
                BEGIN
                    UPDATE termo 
                    SET status = 'IN'
                    WHERE id_processo = NEW.id_processo
                    AND status = 'AT'
                    AND id_termo != NEW.id_termo;
                END;
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS unique_termo_ativo_por_processo_insert;
                DROP TRIGGER IF EXISTS unique_termo_ativo_por_processo_update;
            """
        ),
    ]

