# Generated by Django 6.0.5 on 2026-06-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Setor')),
                ('nome_setor', models.CharField(max_length=20, verbose_name='Nome do Setor')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_origem', models.ForeignKey(db_column='id_origem', on_delete=django.db.models.deletion.PROTECT, to='procurement.origem', verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'db_table': 'setor',
                'ordering': ['id_origem', 'nome_setor'],
                'constraints': [models.UniqueConstraint(fields=('id_origem', 'nome_setor'), name='unique_setor_por_origem')],
            },
        ),
    ]
