# Generated by Django 6.0.5 on 2026-07-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_trigger_unique_termo_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Item')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('PR', 'Produto'), ('SV', 'Serviço')], max_length=2, verbose_name='Tipo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'db_table': 'item',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='procurement.item')),
                ('apresentacao', models.CharField(max_length=20, verbose_name='Apresentação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produto',
                'ordering': ['item_ptr__codigo'],
            },
            bases=('procurement.item',),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Serviço')),
                ('patrimonio', models.CharField(max_length=15, verbose_name='Patrimônio')),
                ('descricao_patrimonio', models.TextField(verbose_name='Descrição do Patrimônio')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_item', models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.PROTECT, to='procurement.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'servico',
                'ordering': ['id_item', 'patrimonio'],
                'constraints': [models.UniqueConstraint(fields=('id_item', 'patrimonio'), name='unique_patrimonio_por_item')],
            },
        ),
    ]
