# Generated by Django 6.0.1 on 2026-04-02 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_processo_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='procurement.servidor', verbose_name='Servidor Responsável'),
        ),
    ]
