# Generated by Django 6.0.5 on 2026-07-09 18:50

import django.core.validators
import django.db.models.deletion
import procurement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_trigger_valida_tipo_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Recurso')),
                ('exercicio', models.IntegerField(default=procurement.models.ano_atual, verbose_name='Exercício')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'recurso',
                'ordering': ['-exercicio', 'id_conta'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID da Conta')),
                ('unidade', models.CharField(max_length=15, verbose_name='Unidade')),
                ('agencia', models.CharField(max_length=6, verbose_name='Agência')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('cnpj', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_cnpj', message='O CNPJ deve conter apenas números.', regex='^\\d+$')], verbose_name='CNPJ')),
                ('funcao', models.CharField(choices=[('PG', 'Pagamento'), ('TR', 'Transferência')], max_length=2, verbose_name='Função')),
                ('categoria_economica', models.CharField(choices=[('CS', 'Custeio'), ('IN', 'Investimento')], max_length=2, verbose_name='Categoria Econômica')),
                ('recurso', models.CharField(choices=[('RG', 'Regular'), ('EM', 'Emenda')], max_length=2, verbose_name='Recurso')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'db_table': 'conta',
                'ordering': ['unidade'],
                'constraints': [models.UniqueConstraint(fields=('unidade', 'agencia', 'numero'), name='unique_conta')],
            },
        ),
        migrations.CreateModel(
            name='Emenda',
            fields=[
                ('recurso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='procurement.recurso')),
                ('oficio', models.CharField(max_length=10, verbose_name='Ofício')),
                ('numero', models.CharField(max_length=12, verbose_name='Número')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor')),
                ('parlamentar', models.CharField(max_length=30, verbose_name='Parlamentar')),
                ('destinacao', models.TextField(verbose_name='Destinação')),
                ('data_recebimento', models.DateField(verbose_name='Data de Recebimento')),
                ('extrato', models.TextField(blank=True, null=True, verbose_name='Extrato')),
                ('sei', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_sei', message='O SEI deve conter apenas números.', regex='^\\d+$')], verbose_name='SEI')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Emenda',
                'verbose_name_plural': 'Emendas',
                'db_table': 'emenda',
                'ordering': ['-recurso_ptr__exercicio', 'parlamentar'],
            },
            bases=('procurement.recurso',),
        ),
        migrations.AddField(
            model_name='recurso',
            name='id_conta',
            field=models.ForeignKey(db_column='id_conta', on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='procurement.conta', verbose_name='Conta'),
        ),
        migrations.CreateModel(
            name='Regular',
            fields=[
                ('id_regular', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Regular')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor')),
                ('data_recebimento', models.DateField(verbose_name='Data de Recebimento')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_recurso', models.ForeignKey(db_column='id_recurso', on_delete=django.db.models.deletion.PROTECT, to='procurement.recurso', verbose_name='Recurso')),
            ],
            options={
                'verbose_name': 'Regular',
                'verbose_name_plural': 'Regulares',
                'db_table': 'regular',
                'ordering': ['-data_recebimento'],
                'constraints': [models.UniqueConstraint(fields=('id_recurso', 'valor', 'data_recebimento'), name='unique_regular')],
            },
        ),
    ]
