# Generated by Django 6.0.5 on 2026-07-09 18:54

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_recurso_conta_emenda_recurso_id_conta_regular'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER valida_tipo_emenda_insert
                BEFORE INSERT ON emenda
                BEGIN
                    SELECT CASE
                        WHEN (SELECT recurso FROM conta
                              WHERE id_conta = (
                                  SELECT id_conta FROM recurso
                                  WHERE id_recurso = NEW.recurso_ptr_id)
                             ) != 'EM'
                        THEN RAISE(ABORT, 'Emendas só podem ser vinculadas a contas do tipo Emenda')
                    END;
                END;

                CREATE TRIGGER valida_tipo_emenda_update
                BEFORE UPDATE ON emenda
                BEGIN
                    SELECT CASE
                        WHEN (SELECT recurso FROM conta
                              WHERE id_conta = (
                                  SELECT id_conta FROM recurso
                                  WHERE id_recurso = NEW.recurso_ptr_id)
                             ) != 'EM'
                        THEN RAISE(ABORT, 'Emendas só podem ser vinculadas a contas do tipo Emenda')
                    END;
                END;

                CREATE TRIGGER valida_tipo_regular_insert
                BEFORE INSERT ON regular
                BEGIN
                    SELECT CASE
                        WHEN (SELECT recurso FROM conta
                              WHERE id_conta = (
                                  SELECT id_conta FROM recurso
                                  WHERE id_recurso = NEW.id_recurso)
                             ) != 'RG'
                        THEN RAISE(ABORT, 'Recursos regulares só podem ser vinculados a contas do tipo Regular')
                    END;
                END;

                CREATE TRIGGER valida_tipo_regular_update
                BEFORE UPDATE ON regular
                BEGIN
                    SELECT CASE
                        WHEN (SELECT recurso FROM conta
                              WHERE id_conta = (
                                  SELECT id_conta FROM recurso
                                  WHERE id_recurso = NEW.id_recurso)
                             ) != 'RG'
                        THEN RAISE(ABORT, 'Recursos regulares só podem ser vinculados a contas do tipo Regular')
                    END;
                END;

                CREATE TRIGGER valida_unique_regular_insert
                BEFORE INSERT ON recurso
                WHEN (SELECT recurso FROM conta WHERE id_conta = NEW.id_conta) = 'RG'
                BEGIN
                    SELECT CASE
                        WHEN EXISTS (
                            SELECT 1 FROM recurso
                            WHERE id_conta = NEW.id_conta
                            AND exercicio = NEW.exercicio
                            AND id_recurso != NEW.id_recurso
                        )
                        THEN RAISE(ABORT, 'Já existe um recurso regular para esta conta neste exercício')
                    END;
                END;

                CREATE TRIGGER valida_unique_regular_update
                BEFORE UPDATE ON recurso
                WHEN (SELECT recurso FROM conta WHERE id_conta = NEW.id_conta) = 'RG'
                BEGIN
                    SELECT CASE
                        WHEN EXISTS (
                            SELECT 1 FROM recurso
                            WHERE id_conta = NEW.id_conta
                            AND exercicio = NEW.exercicio
                            AND id_recurso != NEW.id_recurso
                        )
                        THEN RAISE(ABORT, 'Já existe um recurso regular para esta conta neste exercício')
                    END;
                END;
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS valida_tipo_emenda_insert;
                DROP TRIGGER IF EXISTS valida_tipo_emenda_update;
                DROP TRIGGER IF EXISTS valida_tipo_regular_insert;
                DROP TRIGGER IF EXISTS valida_tipo_regular_update;
                DROP TRIGGER IF EXISTS valida_unique_regular_insert;
                DROP TRIGGER IF EXISTS valida_unique_regular_update;
            """
        ),
    ]


