# Generated by Django 6.0.5 on 2026-08-03 21:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_trigger_valida_tipo_recurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False, verbose_name='ID da Área')),
                ('atuacao', models.TextField(unique=True, verbose_name='Área de Atuação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'area',
                'ordering': ['atuacao'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Fornecedor')),
                ('cnpj_fornecedor', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cnpj', message='O CNPJ deve conter apenas números.', regex='^\\d+$')], verbose_name='CNPJ')),
                ('razao_social', models.TextField(verbose_name='Razão Social')),
                ('nome_fantasia', models.TextField(verbose_name='Nome Fantasia')),
                ('codigo_sis', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código SIS')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedor',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id_contato', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Contato')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contato', models.TextField(verbose_name='Contato')),
                ('telefone', models.TextField(validators=[django.core.validators.RegexValidator(code='invalid_telefone', message='O telefone deve conter apenas números.', regex='^\\d+$')], verbose_name='Telefone')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cnpj_fornecedor', models.ForeignKey(db_column='cnpj_fornecedor', on_delete=django.db.models.deletion.PROTECT, to='procurement.fornecedor', to_field='cnpj_fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'contato',
                'ordering': ['cnpj_fornecedor', 'contato'],
            },
        ),
        migrations.CreateModel(
            name='ContatoArea',
            fields=[
                ('id_contato_area', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Contato Área')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.PROTECT, to='procurement.area', verbose_name='Área')),
                ('id_contato', models.ForeignKey(db_column='id_contato', on_delete=django.db.models.deletion.PROTECT, to='procurement.contato', verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Contato Área',
                'verbose_name_plural': 'Contatos Áreas',
                'db_table': 'contato_area',
                'ordering': ['id_contato', 'id_area'],
                'constraints': [models.UniqueConstraint(fields=('id_contato', 'id_area'), name='unique_contato_area')],
            },
        ),
        migrations.AddIndex(
            model_name='contato',
            index=models.Index(fields=['cnpj_fornecedor'], name='contato_cnpj_fo_3f7cec_idx'),
        ),
        migrations.AddConstraint(
            model_name='contato',
            constraint=models.UniqueConstraint(fields=('cnpj_fornecedor', 'email'), name='unique_email_por_fornecedor'),
        ),
    ]
