# Generated by Django 6.0.5 on 2026-08-05 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_area_fornecedor_contato_contatoarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='atuacao',
            field=models.CharField(max_length=40, unique=True, verbose_name='Área de Atuação'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='contato',
            field=models.CharField(max_length=40, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_telefone', message='O telefone deve conter apenas números.', regex='^\\d+$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='emenda',
            name='extrato',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Extrato'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(max_length=40, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(max_length=100, verbose_name='Razão Social'),
        ),
    ]
