# Generated by Django 6.0.5 on 2026-08-05 22:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_alter_area_atuacao_alter_contato_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Banco')),
                ('codigo_compe', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_codigo_compe', message='O código COMPE deve conter apenas números.', regex='^\\d+$')], verbose_name='Código COMPE')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome do Banco')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'banco',
                'ordering': ['codigo_compe'],
            },
        ),
        migrations.CreateModel(
            name='ContaFornecedor',
            fields=[
                ('id_conta_fornecedor', models.AutoField(primary_key=True, serialize=False, verbose_name='ID da Conta Fornecedor')),
                ('agencia', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_agencia', message='A agência deve conter apenas números.', regex='^\\d+$')], verbose_name='Agência')),
                ('digito_agencia', models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito da Agência')),
                ('conta', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_conta', message='A conta deve conter apenas números.', regex='^\\d+$')], verbose_name='Conta')),
                ('digito_conta', models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito da Conta')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_banco', models.ForeignKey(db_column='id_banco', on_delete=django.db.models.deletion.PROTECT, to='procurement.banco', verbose_name='Banco')),
                ('id_fornecedor', models.OneToOneField(db_column='id_fornecedor', on_delete=django.db.models.deletion.PROTECT, to='procurement.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Conta Fornecedor',
                'verbose_name_plural': 'Contas Fornecedores',
                'db_table': 'conta_fornecedor',
                'ordering': ['id_fornecedor'],
            },
        ),
    ]
