# Generated by Django 6.0.5 on 2026-08-11 19:53

import django.core.validators
import django.db.models.deletion
import procurement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_banco_contafornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteAnual',
            fields=[
                ('id_limite', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Limite')),
                ('ano', models.IntegerField(default=procurement.models.ano_atual, unique=True, verbose_name='Ano')),
                ('valor_limite', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor Limite')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Limite Anual',
                'verbose_name_plural': 'Limites Anuais',
                'db_table': 'limite_anual',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Aquisicao',
            fields=[
                ('id_aquisicao', models.AutoField(primary_key=True, serialize=False, verbose_name='ID da Aquisição')),
                ('quantidade_solicitada', models.IntegerField(verbose_name='Quantidade Solicitada')),
                ('preco', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Preço Unitário')),
                ('quantidade_adquirida', models.IntegerField(blank=True, null=True, verbose_name='Quantidade Adquirida')),
                ('data_ordem', models.DateField(blank=True, null=True, verbose_name='Data da Ordem de Fornecimento')),
                ('sei_dodf', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_sei_dodf', message='O SEI DODF deve conter apenas números.', regex='^\\d+$')], verbose_name='SEI DODF')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_fornecedor', models.ForeignKey(blank=True, db_column='id_fornecedor', null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.fornecedor', verbose_name='Fornecedor')),
                ('id_item', models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.PROTECT, to='procurement.item', verbose_name='Item')),
                ('id_recurso', models.ForeignKey(blank=True, db_column='id_recurso', null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.recurso', verbose_name='Recurso')),
                ('id_servico', models.ForeignKey(blank=True, db_column='id_servico', null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.servico', verbose_name='Serviço')),
                ('id_termo', models.ForeignKey(db_column='id_termo', on_delete=django.db.models.deletion.PROTECT, to='procurement.termo', verbose_name='Termo')),
            ],
            options={
                'verbose_name': 'Aquisição',
                'verbose_name_plural': 'Aquisições',
                'db_table': 'aquisicao',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='LogAquisicao',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Log')),
                ('campo_alterado', models.CharField(max_length=30, verbose_name='Campo Alterado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('id_aquisicao', models.ForeignKey(db_column='id_aquisicao', on_delete=django.db.models.deletion.PROTECT, to='procurement.aquisicao', verbose_name='Aquisição')),
                ('id_servidor', models.ForeignKey(blank=True, db_column='id_servidor', null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.servidor', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Log de Aquisição',
                'verbose_name_plural': 'Logs de Aquisição',
                'db_table': 'log_aquisicao',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.AddIndex(
            model_name='aquisicao',
            index=models.Index(fields=['id_termo'], name='aquisicao_id_term_a06ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='aquisicao',
            index=models.Index(fields=['id_item'], name='aquisicao_id_item_bf5bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='aquisicao',
            index=models.Index(fields=['id_fornecedor'], name='aquisicao_id_forn_d32224_idx'),
        ),
        migrations.AddIndex(
            model_name='aquisicao',
            index=models.Index(fields=['id_recurso'], name='aquisicao_id_recu_8ccb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='aquisicao',
            index=models.Index(fields=['data_ordem'], name='aquisicao_data_or_a81d48_idx'),
        ),
    ]
