# Generated by Django 6.0.5 on 2026-08-19 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_trigger_valida_aquisicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id_nota_fiscal', models.AutoField(primary_key=True, serialize=False, verbose_name='ID da Nota Fiscal')),
                ('numero_nf', models.CharField(max_length=10, verbose_name='Número da Nota Fiscal')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('total_nf', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Total da Nota Fiscal')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('data_atesto', models.DateField(blank=True, null=True, verbose_name='Data de Atesto')),
                ('reinf', models.BooleanField(default=False, verbose_name='REINF')),
                ('optante_simples', models.BooleanField(blank=True, null=True, verbose_name='Optante do Simples Nacional')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_fornecedor', models.ForeignKey(db_column='id_fornecedor', on_delete=django.db.models.deletion.PROTECT, to='procurement.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'db_table': 'nota_fiscal',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Pagamento')),
                ('quantidade_paga', models.IntegerField(verbose_name='Quantidade Paga')),
                ('numero_pagamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número do Pagamento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('registro_sei', models.BooleanField(default=False, verbose_name='Registro SEI')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('id_aquisicao', models.ForeignKey(db_column='id_aquisicao', on_delete=django.db.models.deletion.PROTECT, to='procurement.aquisicao', verbose_name='Aquisição')),
                ('id_nota_fiscal', models.ForeignKey(db_column='id_nota_fiscal', on_delete=django.db.models.deletion.PROTECT, to='procurement.notafiscal', verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pagamento',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['id_fornecedor'], name='nota_fiscal_id_forn_f87416_idx'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(fields=('id_fornecedor', 'numero_nf'), name='unique_nf_por_fornecedor'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['id_aquisicao'], name='pagamento_id_aqui_9068c5_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['id_nota_fiscal'], name='pagamento_id_nota_411d0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.UniqueConstraint(fields=('id_aquisicao', 'id_nota_fiscal'), name='unique_pagamento_por_aquisicao_nf'),
        ),
    ]
