# Generated by Django 6.0.5 on 2026-08-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_notafiscal_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='id_servidor',
            field=models.CharField(help_text='Matrícula funcional do servidor (apenas números)', max_length=20, primary_key=True, serialize=False, verbose_name='Matrícula'),
        ),
    ]
