# Generated by Django 6.0.5 on 2026-08-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_alter_servidor_id_servidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquisicao',
            name='sei_dodf',
        ),
        migrations.AddField(
            model_name='aquisicao',
            name='upload_dodf',
            field=models.BooleanField(default=False, verbose_name='Upload DODF'),
        ),
    ]
