# Generated by Django 6.0.1 on 2026-09-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_remove_aquisicao_sei_dodf_aquisicao_upload_dodf'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquisicao',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
        migrations.AddField(
            model_name='aquisicao',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
